version: '3.8'

services:
  soccerbot:
    build: .
    container_name: soccerbot
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      # Volume para persistir banco de dados JSON
      - ./db.json:/usr/src/app/db.json
      
      # Volume para persistir arquivo .env (variáveis de ambiente)
      - ./.env:/usr/src/app/.env:ro
    environment:
      - NODE_ENV=production
    networks:
      - soccerbot-network

networks:
  soccerbot-network:
    driver: bridge

