module.exports = [
  "{nome}, olha quem apareceu! A gente nunca sabe o que esperar de você!",
  "Com {nome} no time, temos mais chances de... pelo menos tentar!",
  "Não tem como perder com {nome} no nosso lado... só de pensar já dá medo!",
  "{nome}, a bola já sabe que tem que evitar seus pés!",
  "O craque {nome} chegou... para deixar o jogo mais divertido!",
  "Nosso segredo para a vitória: {nome} fora do campo!",
  "Com {nome} em campo, a goleada é certa... para o outro time!",
  "{nome}, você é a peça que faz o quebra-cabeça ficar mais difícil!",
  "Os adversários já estão rindo só de pensar em enfrentar {nome}!",
  "{nome}, hoje o estádio vai ver o que é esforço, mesmo sem talento!",
  "{nome}, o campo está pronto para ver seus tropeços incríveis!",
  "Com {nome} no time, a vitória é questão de sorte!",
  "{nome}, hoje o gol vai ser uma raridade se depender de você!",
  "O time está completo com {nome} entre nós... literalmente!",
  "{nome}, sua presença torna tudo mais... imprevisível!",
  "{nome}, você veio para ser o destaque... pelos motivos errados!",
  "{nome}, a bola sabe que está em perigo nos seus pés!",
  "{nome}, hoje é o seu dia de tentar não atrapalhar!",
  "Com {nome} no time, a defesa adversária vai ter um dia tranquilo!",
  "{nome}, seu talento é a nossa maior surpresa... quando aparece!",
  "{nome}, só você para fazer aquele gol... na trave!",
  "{nome}, com você no time, os nossos sonhos se tornam desafios!",
  "{nome}, você é o motivo do nosso sorriso... nervoso!",
  "{nome}, a torcida está ansiosa para ver seus deslizes!",
  "Com {nome} em campo, a nossa moral está... balançando!",
  "{nome}, você é o nosso capitão... de comédia!",
  "{nome}, o time está contando com a sua... presença!",
  "{nome}, cada jogada sua é um espetáculo de... superação!",
  "{nome}, sua determinação é o nosso combustível para... rir!",
  "{nome}, você é a prova viva de que qualquer um pode jogar!",
  "{nome}, com você, o nosso time é mais... animado!",
  "{nome}, você é a nossa estrela... cadente!",
  "{nome}, hoje vamos celebrar a sua... coragem de tentar!",
  "{nome}, a vitória está a um passo de distância... de você!",
  "{nome}, cada lance seu é um exemplo de garra e... tentativa!",
  "{nome}, seu nome já está gravado na história... das piadas!",
  "{nome}, você é o nosso raio de esperança... para melhorar!",
  "{nome}, com você, até os desafios se tornam... engraçados!",
  "{nome}, você transforma o campo em um palco de... comédia!",
  "{nome}, com você, somos... únicos!",
  "{nome}, o nosso time é mais feliz com você aqui... para rir!",
  "{nome}, sua paixão pelo jogo é... admirável!",
  "{nome}, você é a personificação da... diversão!",
  "{nome}, hoje é o dia de fazer história... engraçada!",
  "{nome}, sua presença eleva o nível de... diversão!",
  "{nome}, com você, somos um time... especial!",
  "{nome}, você é o nosso ídolo... do humor!",
  "{nome}, a sua dedicação nos inspira a... persistir!",
  "{nome}, você é a prova de que... qualquer um pode jogar!",
  "{nome}, cada jogada sua é um passo rumo ao... inesperado!",
  "{nome}, o campo é o seu território de... diversão!",
  "{nome}, com você, o impossível se torna... mais divertido!",
  "{nome}, seu talento é a nossa maior... surpresa!",
  "{nome}, sua habilidade nos faz acreditar na... possibilidade!",
  "{nome}, o nosso time é mais forte com você... em espírito!",
  "{nome}, seu espírito de equipe é o nosso maior trunfo... de risadas!",
  "{nome}, com você, todos os obstáculos se tornam... mais leves!",
  "{nome}, seu amor pelo jogo nos une ainda mais... na diversão!",
  "{nome}, sua determinação é o nosso escudo contra a... seriedade!",
  "{nome}, você é a inspiração que precisamos para... rir!",
  "{nome}, cada partida com você é uma festa de... risadas!",
  "{nome}, você transforma o campo em um lugar... animado!",
  "{nome}, a sua garra contagia todo o time... de alegria!",
  "{nome}, você é a razão pela qual amamos... brincar!",
  "{nome}, com você, o nosso time é uma família... de risadas!",
  "{nome}, hoje vamos fazer história... engraçada!",
  "{nome}, sua persistência é a nossa força motriz... de diversão!",
  "{nome}, o campo é o seu palco de... piadas!",
  "{nome}, seu talento faz a diferença em cada lance... de humor!",
  "{nome}, com você, a vitória é certa... de risos!",
  "{nome}, sua presença eleva o nível de jogo de todos... na alegria!",
  "{nome}, hoje vamos deixar o mundo do futebol... sorrindo!",
  "{nome}, sua habilidade é a nossa arma secreta... de humor!",
  "{nome}, com você, somos... únicos!",
  "{nome}, cada partida com você é uma experiência... divertida!",
  "{nome}, sua determinação nos leva rumo à... diversão!",
  "{nome}, o seu talento é a nossa maior... piada!",
  "{nome}, com você, cada gol é uma obra de... tentativa!",
  "{nome}, hoje é o dia de brilhar... na comédia!",
  "{nome}, você é o nosso líder dentro e fora do campo... de diversão!",
  "{nome}, sua vontade de vencer é nossa maior... piada!",
  "{nome}, com você, o nosso time é uma... comédia!",
  "{nome}, sua técnica é o nosso segredo para o... humor!",
  "{nome}, o jogo fica mais emocionante com você em campo... de risos!",
  "{nome}, com você, todos os dias são dias de... diversão!",
  "{nome}, sua paixão pelo futebol nos une ainda mais... na alegria!",
  "{nome}, você é a personificação da... diversão!",
  "{nome}, hoje vamos mostrar ao mundo do que somos capazes... de rir!",
  "{nome}, com você, cada desafio se torna uma... risada!",
  "{nome}, você é o nosso exemplo vivo de... humor!",
  "{nome}, sua presença transforma o nosso time em uma equipe... feliz!",
  "{nome}, seus dribles são a nossa jogada secreta... de humor!",
  "{nome}, com você, cada jogo é uma celebração de... risadas!",
  "{nome}, sua humildade inspira... sorrisos!",
  "{nome}, hoje vamos fazer história... divertida!",
  "{nome}, sua determinação é a nossa força motriz... de risos!",
  "{nome}, com você, somos um time... feliz!",
  "{nome}, sua garra é o nosso maior orgulho... de diversão!",
  "{nome}, cada gol seu é um passo rumo à... alegria!",
  "{nome}, o nosso time é mais forte com você... na alegria!"
];
